/**
 * EVEREST — a cinematic technical illustration, constructed.
 *
 * NOT a photograph, not a logo, not a triangle. This is the Khumbu skyline as a
 * matte painting assembled from geometric facets: the summit pyramid, the
 * Southeast Ridge stepping down to the South Col, Lhotse across the saddle, and
 * the Nuptse wall closing the foreground.
 *
 * WHY THE GEOMETRY IS GENERATED, NOT TYPED
 *
 * A mountain drawn as ~200 hand-written polygon strings is unreadable and
 * untunable — moving the summit 40px left means editing every coordinate. So
 * the massif is built from RIDGES: polylines generated by two functions with a
 * handful of shape parameters. Faces are the quads BETWEEN consecutive ridges.
 * That gives the real structure of a big face — buttresses and the gullies
 * between them — and the whole mountain re-proportions from a few numbers.
 *
 * PROPORTION IS THE WHOLE GAME
 *
 * Everest from the south is a BROAD wedge, not a spike. Its West Ridge runs out
 * at barely 30 degrees and takes most of a horizon to come down. The first
 * build of this file used a steep falloff and produced a needle — correct in
 * its parts, wrong at a glance, and wrong at a glance is just wrong. The ridge
 * exponents below are the fix, and they are the most load-bearing numbers here.
 *
 * THE TEN-VALUE RULE
 *
 * Every facet indexes into `--tr0..--tr9`. There are ten values in this
 * painting, not two hundred. That constraint is what keeps a heavily faceted
 * illustration from turning to gravel: shapes group into readable planes
 * because they share exact values, the way a screen print does.
 *
 * Because those ten values are CSS custom properties, a theme switch re-skins
 * the entire mountain with NO React render — the attribute flips on <html> and
 * every polygon follows. Dark mode is a different hour, not an inversion.
 *
 * EVERYTHING IS CLIPPED TO ITS OWN SILHOUETTE. Facets are generated, so they
 * overshoot the outline by design; the clip is what lets the generators stay
 * simple instead of every ridge having to solve for where it meets the skyline.
 *
 * LIGHT COMES FROM THE UPPER LEFT, always.
 */

export const VIEW = { w: 1600, h: 900 }

const round = (n) => Math.round(n * 10) / 10
const pts = (list) => list.map(([x, y]) => `${round(x)},${round(y)}`).join(' ')

/**
 * Terrain ramp lookup: 0 (deepest shadow) -> 1 (brightest snow).
 *
 * Deliberately QUANTISED to the ten ramp steps rather than interpolated. Two
 * facets given 0.61 and 0.64 resolve to the same value and merge into one
 * plane, which is exactly the grouping that makes a face readable.
 */
export const tr = (v) => `var(--tr${Math.max(0, Math.min(9, Math.round(v * 9)))})`

/* ----------------------------------------------------------------- ridges */

const STEPS = 10

/**
 * Deterministic value noise in -1..1.
 *
 * `Math.random()` is unusable here: the mountain would reshuffle on every
 * render and differ between the first paint and every one after. A hash of the
 * index is stable forever and still looks arbitrary, which is the only property
 * that matters.
 */
const noise = (n) => {
  const s = Math.sin(n * 127.1) * 43758.5453
  return (s - Math.floor(s)) * 2 - 1
}

/**
 * A FACE ridge: falls from the summit region to the bottom of the frame.
 *
 * The exponents are the shape language. y grows slightly faster than linear so
 * detail concentrates near the summit; x grows a little slower than linear so
 * the profile is gently concave — near-vertical up high, flaring into the base.
 * At 1.28 (the first attempt) this produced a needle; 1.06 produces a mountain.
 *
 * JITTER IS THE DIFFERENCE BETWEEN ROCK AND A TENT.
 *
 * With smooth ridges, every facet between two of them is a long clean triangle
 * converging on the apex, and a fan of clean triangles is read by the eye as
 * PLEATS — a circus tent, a folded paper fan, anything but a mountain. No
 * amount of shading fixes it, because the problem is the edges.
 *
 * Real ridges zigzag. Displacing each interior point by a stable hash turns
 * every facet into an irregular quad, and the face immediately reads as broken
 * rock. The displacement tapers to zero at both ends (the `sin` envelope) so
 * ridges still meet the summit and the base exactly where they are told to.
 */
function faceRidge(top, bottomX, bow = 0, seed = 1) {
  const out = []
  for (let i = 0; i < STEPS; i += 1) {
    const t = i / (STEPS - 1)
    const envelope = Math.sin(t * Math.PI)
    out.push([
      top[0] +
        (bottomX - top[0]) * t ** 1.06 +
        Math.sin(t * Math.PI) * bow +
        noise(seed * 31.7 + i * 17.3) * 34 * envelope,
      top[1] + (VIEW.h - top[1]) * t ** 0.94 + noise(seed * 57.1 + i * 13.9) * 26 * envelope,
    ])
  }
  return out
}

/** The quad strip between two ridges, from step `from` to step `to`. */
function band(a, b, from, to) {
  return [...a.slice(from, to + 1), ...b.slice(from, to + 1).reverse()]
}

/* --------------------------------------------------------------- the massif */

/**
 * The main summit, placed at 63% across and 24% down.
 *
 * High enough to dominate, low enough that the entire top-left quadrant is open
 * air for the headline. The composition is a diagonal: type top-left, summit
 * upper-right, the Nuptse wall closing the bottom.
 */
export const APEX = [1006, 216]

/**
 * The SOUTHEAST RIDGE — the standard route's skyline, and the single feature
 * that makes this mountain identifiable as Everest rather than as a peak.
 *
 * It leaves the summit, drops to the notch above the Hillary Step, rises over
 * the SOUTH SUMMIT, then falls in a long sweep to the SOUTH COL at 7,906m.
 * That saddle is the lowest point between Everest and Lhotse and the reason the
 * two read as one massif with a bite taken out of it.
 */
export const SE_RIDGE = [
  APEX,
  [1030, 238],
  [1048, 264],
  [1064, 280], // the notch — the Hillary Step sits in here
  [1086, 292], // South Summit
  [1108, 322],
  [1134, 358],
  [1166, 404],
  [1200, 450],
  [1238, 488],
  [1276, 512],
  [1310, 528], // SOUTH COL
]

/**
 * The WEST RIDGE — hand-authored, because its whole job is to be irregular.
 *
 * A generated ridge gave a clean monotonic sweep, and a clean sweep either side
 * of a summit is a CONE. The eye reads a circus tent, not a mountain, and no
 * amount of facet detail inside the silhouette rescues it — silhouette is read
 * first and it overrides everything.
 *
 * The fix is the WEST SHOULDER: the real ridge drops off the summit, then flattens
 * into a long near-level terrace around 7,000m before falling away again. That
 * one interruption is what makes the profile read as a specific mountain rather
 * than as a shape. It also breaks the symmetry with the Southeast Ridge, so the
 * summit stops sitting in the middle of an isosceles triangle.
 *
 * It runs out of the frame rather than reaching the ground, which is what sells
 * the massif as bigger than the picture.
 */
const WEST_RIDGE = [
  APEX,
  [958, 250],
  [910, 292],
  [864, 338],
  [820, 384],
  [778, 426],
  [734, 462],
  [688, 484], // the shoulder begins
  [628, 496],
  [566, 508], // ~7,000m terrace: near level for 160px
  [506, 528],
  [448, 560],
  [386, 596],
  [318, 630],
  [246, 660],
  [166, 686],
  [76, 710],
  [-70, 742],
]

/** The face, as a fan of ridges falling to the bottom edge. */
const FACE_TOPS = [
  [960, 288],
  [978, 252],
  [994, 228],
  [1018, 226],
  [1040, 250],
  [1062, 282],
  [1088, 316],
]
const FACE_BASES = [96, 268, 440, 616, 792, 960, 1120]
const FACE_BOWS = [40, -26, 30, -18, 24, -30, 16]

/**
 * Base value per rib.
 *
 * Two gradients at once: overall brightness falls left-to-right as the face
 * turns away from the light, AND consecutive ribs alternate. The alternation is
 * the important half — it reads as buttress / gully / buttress rather than as a
 * smoothly shaded cone.
 */
const FACE_LIT = [0.5, 0.34, 0.45, 0.28, 0.4, 0.24, 0.33]

/**
 * Where snow stops holding on each rib, as a step index. Varied so the snowline
 * is RAGGED — a snowline at a constant altitude is the clearest tell of a
 * generated mountain, because real snow sits deep on the sheltered ribs and is
 * stripped off the windward ones.
 */
const SNOW_TO = [2, 1, 3, 2, 3, 2, 2]
/** And where the mid-face terrace gives way to the lower, hazier rock. */
const MID_TO = [6, 5, 6, 6, 5, 5, 5]

const FACE_RIDGES = FACE_TOPS.map((top, i) => faceRidge(top, FACE_BASES[i], FACE_BOWS[i], i + 2))
/** The right bound of the face, falling from the ridge below the South Summit. */
const EAST_BOUND = faceRidge([1088, 316], 1290, 10, 11)

/** Left-to-right, the full set of dividing lines across the face. */
const RIDGES = [faceRidge([948, 320], -60, 30, 1), ...FACE_RIDGES, EAST_BOUND]

/** The massif silhouette: up the West Ridge to the apex, then down the SE ridge. */
const MASSIF_OUTLINE = [
  [-70, VIEW.h],
  ...WEST_RIDGE.slice().reverse(),
  ...SE_RIDGE.slice(1),
  [1310, VIEW.h],
]

/* ------------------------------------------------------------------ Lhotse */

/**
 * LHOTSE, 8,516m — the fourth-highest mountain on earth, and from the south it
 * is inseparable from Everest.
 *
 * Drawn as a much sharper pyramid than Everest: Everest's summit is a broad
 * wedge, Lhotse's is a spike. That contrast does identification work — two
 * peaks of the same shape either side of a saddle would read as a mountain
 * range, where a wedge and a spike read as Everest and Lhotse.
 */
const LHOTSE_APEX = [1452, 300]
const LHOTSE_OUTLINE = [
  [1310, 528],
  [1344, 476],
  [1372, 428],
  [1400, 378],
  [1428, 330],
  LHOTSE_APEX,
  [1478, 342],
  [1506, 392],
  [1534, 450],
  [1562, 516],
  [1590, 592],
  [1670, 800],
  [1670, VIEW.h],
  [1310, VIEW.h],
]

/**
 * The Lhotse Face — 1,100m of blue ice, so these ribs run BRIGHTER than
 * Everest's rock and closer together in value. It is a sheet, not a set of
 * buttresses, and should read as one cold plane with structure in it.
 */
const LHOTSE_RIDGES = [
  faceRidge(LHOTSE_APEX, 1316, 10, 21),
  faceRidge([1444, 316], 1392, 6, 22),
  faceRidge([1462, 320], 1470, -6, 23),
  faceRidge([1482, 350], 1548, -10, 24),
  faceRidge([1506, 392], 1628, -8, 25),
]
const LHOTSE_LIT = [0.46, 0.64, 0.4, 0.56, 0.34]

/* ------------------------------------------------------------------ Nuptse */

/**
 * THE NUPTSE WALL — the foreground, and the reason the composition has depth.
 *
 * Nuptse is only 7,861m but stands kilometres closer to the viewer, so it
 * occludes the entire base of Everest. That single occlusion does more for
 * scale than any amount of shading: the eye reads "the big peak is BEHIND the
 * near wall, and still towers over it", and the massif goes from tall to
 * enormous.
 *
 * SERRATION IS LOW-AMPLITUDE ON PURPOSE. The first build gave it 60px teeth and
 * it read as a sawblade — a row of triangles, not a mountain. A real serrated
 * crest varies by a fraction of the wall's height; the wall is the mass and the
 * teeth are an inflection on top of it.
 *
 * Being nearest, it carries the least haze and so the most contrast — nearly a
 * silhouette against a mountain that is comparatively pale.
 */
const NUPTSE_CREST = [
  [-70, 618],
  [58, 598],
  [140, 610],
  [214, 578],
  [292, 594],
  [352, 566], // pinnacle
  [416, 600],
  [486, 584],
  [548, 552], // the wall's high point
  [608, 590],
  [676, 578],
  [738, 606],
  [800, 582],
  [864, 604],
  [928, 590],
  [990, 618],
  [1054, 602],
  [1120, 632],
  [1186, 620],
  [1252, 652],
  [1320, 676],
  [1396, 704],
  [1476, 734],
  [1566, 766],
  [1670, 800],
]
const NUPTSE_OUTLINE = [...NUPTSE_CREST, [1670, VIEW.h], [-70, VIEW.h]]

/* ------------------------------------------------------------- far ranges */

/** Distant Himalaya. Two rows, both almost dissolved into the air. */
const RANGE_FAR = [
  [-70, 636],
  [70, 570],
  [168, 606],
  [274, 546],
  [372, 590],
  [470, 532],
  [566, 578],
  [660, 540],
  [742, 588],
  [820, 560],
  [900, 604],
  [980, 640],
  [980, VIEW.h],
  [-70, VIEW.h],
]

const RANGE_MID = [
  [-70, 690],
  [86, 632],
  [196, 664],
  [312, 616],
  [424, 656],
  [536, 612],
  [634, 650],
  [724, 626],
  [800, 664],
  [880, 690],
  [880, VIEW.h],
  [-70, VIEW.h],
]

/* ===========================================================================
   COMPONENTS
   =========================================================================== */

/**
 * The massif.
 *
 * Painted back to front in one pass: silhouette, then the face broken into
 * three altitude zones per rib (snow / terrace / lower rock), then couloir and
 * crevasse detail, then the summit cap last so it sits on top of everything.
 */
export function EverestMassif({ id }) {
  return (
    <g>
      <clipPath id={`${id}-massif`}>
        <polygon points={pts(MASSIF_OUTLINE)} />
      </clipPath>

      {/* The silhouette. Everything after this is clipped into it, so a facet
          that overshoots shows the massif colour and never the sky. */}
      <polygon points={pts(MASSIF_OUTLINE)} fill={tr(0.22)} />

      <g clipPath={`url(#${id}-massif)`}>
        {/* ------------------------------------------------ the face, in zones */}
        {RIDGES.slice(0, -1).map((left, i) => {
          const right = RIDGES[i + 1]
          const lit = FACE_LIT[Math.min(i, FACE_LIT.length - 1)]
          const snowTo = SNOW_TO[Math.min(i, SNOW_TO.length - 1)]
          const midTo = MID_TO[Math.min(i, MID_TO.length - 1)]

          return (
            <g key={`face-${i}`}>
              {/* Lower rock — furthest from the light and closest to the haze
                  pooling at the base, so the darkest zone on the face. */}
              <polygon points={pts(band(left, right, midTo, STEPS - 1))} fill={tr(lit * 0.6)} />
              {/* The mid-face terrace. */}
              <polygon points={pts(band(left, right, snowTo, midTo))} fill={tr(lit)} />
              {/*
                Snow held on the upper rib.

                +0.26 and confined to one or two steps. At +0.32 across three
                steps these became enormous pale triangles fanning half the
                height of the mountain, and the face read as overlapping sheets
                of frosted glass rather than as rock — the ribs stopped being
                structure and became transparency. A big face is mostly DARK
                rock; snow is the exception on it, and the summit cap below is
                the only place the ramp is allowed to reach the top.
              */}
              <polygon
                points={pts(band(left, right, 0, snowTo))}
                fill={tr(Math.min(0.82, lit + 0.26))}
              />
            </g>
          )
        })}

        {/*
          The flank falling east toward the South Col. Turned fully away from
          the light, so it goes nearly black — and that is precisely what makes
          the South Col read as a gap rather than as a drawn line.
        */}
        {/* 0.13 made this a black void beside the summit — a shark fin cut out
            of the sky rather than a face turned away from the light. 0.19 still
            reads as the shadow side and still opens the col. */}
        <polygon
          points={pts([...EAST_BOUND, [1310, VIEW.h], ...SE_RIDGE.slice(7).reverse()])}
          fill={tr(0.19)}
        />

        {/*
          COULOIRS — snow-choked gullies on the shadowed ribs.

          Confined to the upper half of the face and to the ribs that are
          otherwise dark. Real faces work exactly this way: snow survives in the
          gullies the sun and wind cannot reach, so the darkest parts of a face
          carry the brightest lines. The detail that rewards actually looking.
        */}
        {[2, 4, 6].map((i) => {
          const left = RIDGES[i]
          const right = RIDGES[i + 1]
          const mix = (t) =>
            left.map(([lx, ly], k) => [lx + (right[k][0] - lx) * t, ly + (right[k][1] - ly) * t])
          /*
             Kept SHORT and quiet. Run to step 4 at 0.42 opacity they became two
             pale streaks raking the whole face — read as light rays crossing
             the mountain rather than as snow lying in it, which is a worse
             artefact than the detail was worth.
          */
          return (
            <polygon
              key={`couloir-${i}`}
              points={pts(band(mix(0.38), mix(0.5), 1, 5))}
              fill={tr(FACE_LIT[i - 1] + 0.3)}
              opacity="0.28"
            />
          )
        })}

        {/*
          STRATA — the horizontal half of the face.

          Everest's south side is layered sedimentary rock, and two of its bands
          are famous enough to be route landmarks: the YELLOW BAND of limestone
          around 7,600m, and the darker step of the Geneva Spur beneath it.

          They are here for a compositional reason as much as a geological one.
          The ribs above are all radial, and radial lines alone converge on the
          apex and read as pleats in a tent. Crossing them with horizontal
          strata turns the face into a GRID of facets — and a grid reads as
          rock, gives the eye a sense of scale, and destroys the cone.

          Tilted slightly, because bedding planes are never level, and drawn at
          low opacity so they modulate the ribs rather than replacing them.
        */}
        {[
          { a: [-70, 372], b: [1200, 300], h: 46, v: 0.82, o: 0.16 },
          { a: [-70, 470], b: [1240, 384], h: 30, v: 0.1, o: 0.2 },
          { a: [-70, 556], b: [1280, 470], h: 58, v: 0.62, o: 0.11 },
          { a: [-70, 690], b: [1300, 604], h: 40, v: 0.06, o: 0.22 },
        ].map((s, i) => (
          <polygon
            key={`strata-${i}`}
            points={pts([s.a, s.b, [s.b[0], s.b[1] + s.h], [s.a[0], s.a[1] + s.h]])}
            fill={tr(s.v)}
            opacity={s.o}
          />
        ))}

        {/* The bergschrund, where the upper snowfields break from the face. */}
        <path
          d="M812 452 C 900 398, 1010 376, 1112 414"
          stroke={tr(0.84)}
          strokeWidth="2"
          fill="none"
          opacity="0.34"
        />

        {/* Crevasse hairlines. At this distance a crevasse is a value break,
            never a drawn shape. */}
        <g stroke={tr(0.3)} strokeWidth="1.6" fill="none" opacity="0.5">
          <path d="M946 316 C 984 328, 1026 326, 1062 314" />
          <path d="M904 372 C 962 390, 1030 386, 1084 368" />
          <path d="M1108 336 C 1136 352, 1158 366, 1182 376" />
        </g>
      </g>

      {/*
        THE SUMMIT SNOW CAP.

        Everest's summit is not a point of rock — it is a small, slightly domed
        snowfield, the last thing on the mountain to hold light. The brightest
        value on the page, and the only place tr9 appears at full strength.
      */}
      <polygon
        points={pts([
          [960, 288],
          [978, 252],
          [994, 228],
          APEX,
          [1030, 238],
          [1048, 264],
          [1064, 280],
          [1042, 300],
          [1004, 306],
          [974, 302],
        ])}
        fill={tr(0.99)}
      />
      {/* The cap's own shadow side, so it reads as a dome and not a decal. */}
      <polygon
        points={pts([APEX, [1030, 238], [1048, 264], [1064, 280], [1042, 300], [1010, 286]])}
        fill={tr(0.76)}
      />

      {/*
        THE SUMMIT RIDGE, lit.

        One hairline of the brightest value along the skyline from the apex to
        the South Summit. Real summit ridges catch light on the windward cornice
        and separate from the sky by a hard edge; without it the top of the
        pyramid dissolves into the atmosphere and the peak loses its point.
      */}
      <polyline
        points={pts(SE_RIDGE.slice(0, 5))}
        fill="none"
        stroke={tr(1)}
        strokeWidth="2.4"
        strokeLinecap="round"
        opacity="0.92"
      />
      <polyline
        points={pts(WEST_RIDGE.slice(0, 4))}
        fill="none"
        stroke={tr(0.95)}
        strokeWidth="2"
        strokeLinecap="round"
        opacity="0.5"
      />
    </g>
  )
}

/** Lhotse, across the South Col. */
export function Lhotse({ id }) {
  return (
    <g>
      <clipPath id={`${id}-lhotse`}>
        <polygon points={pts(LHOTSE_OUTLINE)} />
      </clipPath>

      <polygon points={pts(LHOTSE_OUTLINE)} fill={tr(0.19)} />

      <g clipPath={`url(#${id}-lhotse)`}>
        {LHOTSE_RIDGES.slice(0, -1).map((left, i) => (
          <g key={`lhotse-${i}`}>
            <polygon
              points={pts(band(left, LHOTSE_RIDGES[i + 1], 4, STEPS - 1))}
              fill={tr(LHOTSE_LIT[i] * 0.58)}
            />
            <polygon
              points={pts(band(left, LHOTSE_RIDGES[i + 1], 0, 4))}
              fill={tr(LHOTSE_LIT[i] + 0.24)}
            />
          </g>
        ))}

        <path
          d="M1336 512 C 1400 448, 1466 430, 1530 470"
          stroke={tr(0.78)}
          strokeWidth="2"
          fill="none"
          opacity="0.32"
        />
      </g>

      {/* Lit summit edge — the same treatment as Everest, one step quieter, so
          Lhotse reads as the second subject rather than as a rival. */}
      <polyline
        points={pts([[1400, 378], [1428, 330], LHOTSE_APEX, [1478, 342]])}
        fill="none"
        stroke={tr(0.92)}
        strokeWidth="2"
        strokeLinecap="round"
        opacity="0.6"
      />
    </g>
  )
}

/**
 * The Nuptse wall.
 *
 * Its signature is FLUTINGS — near-vertical ribs of snow and ice hanging off
 * the crest, carved by spindrift. Drawn as narrow tapering strips, they give
 * the eye vertical structure and scale across 1,700px of otherwise flat dark
 * shape. Drawn as wide triangles (the first attempt) they read as teeth, which
 * is why they are narrow and shallow here.
 */
export function Nuptse({ id }) {
  /*
   * THE WALL IS FACETED, NOT FLAT.
   *
   * Earlier passes drew a flat near-black polygon with thin flutings hanging
   * off the crest, and it read as a fringed curtain across the bottom quarter
   * of the screen — 250px of dead ink with a decorative edge. A quarter of the
   * hero cannot be a void.
   *
   * So the wall is built the same way the massif is: a plane between each pair
   * of crest points, dropping to the frame edge, each one a slightly different
   * value. Alternating faces read as the buttresses of a wall seen end-on, and
   * the whole foreground gains structure while staying dark enough to sit in
   * front of everything else.
   */
  /*
   * THE WALL IS A TILED SURFACE, NOT A ROW OF SHAPES.
   *
   * Two builds failed here for the same reason. Each crest segment was given
   * its own independent quad, so adjacent faces did not share vertices — they
   * overlapped and gapped, every face kept its own hard left and right edge,
   * and the result read as a stockade of columns (full height) and then as a
   * row of concrete blocks (cropped). Both times the wall looked like objects
   * standing in front of the mountain rather than a surface belonging to it.
   *
   * The fix is a shared BASE line: one vertex per crest vertex, offset down and
   * damped toward a mean. Face `i` spans crest[i]-crest[i+1]-base[i+1]-base[i],
   * so consecutive faces share an entire edge exactly. The surface is now
   * continuous by construction — the facets are seams in one plane instead of
   * boundaries between separate ones — and values only ever differ by a step or
   * two, so the eye reads modulation rather than a pattern.
   */
  /*
   * A SHALLOW crest band, and nothing else below it.
   *
   * The detail budget of this illustration belongs to Everest. Every attempt to
   * model the foreground wall in depth — full-height faces, cropped faces,
   * tiled faces — produced something that competed with the summit and lost:
   * the eye kept going to a row of grey slabs at the bottom of the frame
   * instead of to the mountain, in both themes but glaringly in daylight.
   *
   * A cinematic foreground is a SILHOUETTE. So the wall is one dark mass and
   * the only modelling is a shallow band where the light actually lands, along
   * the crest. The band still tiles (shared vertices, no seams), but at ~70px
   * against a 280px wall it reads as a lit edge on a dark shape — which is
   * exactly what it is — instead of as a row of objects.
   */
  const BASE = NUPTSE_CREST.map(([x, y], i) => [
    x + noise(i * 9.3) * 16,
    y + 58 + noise(i * 4.7) * 24,
  ])

  const faces = NUPTSE_CREST.slice(0, -1).map(([x, y], i) => (
    <polygon
      key={`nf-${i}`}
      points={pts([[x, y], NUPTSE_CREST[i + 1], BASE[i + 1], BASE[i]])}
      fill={tr(i % 2 ? 0.28 : 0.2)}
    />
  ))

  return (
    <g>
      <clipPath id={`${id}-nuptse`}>
        <polygon points={pts(NUPTSE_OUTLINE)} />
      </clipPath>

      <polygon points={pts(NUPTSE_OUTLINE)} fill={tr(0.08)} />

      <g clipPath={`url(#${id}-nuptse)`}>
        {faces}

        {/* The lit crest line — thin, and what stops a near-black mass reading
            as a hole punched in the page. */}
        <polyline
          points={pts(NUPTSE_CREST)}
          fill="none"
          stroke={tr(0.6)}
          strokeWidth="2.2"
          strokeLinejoin="round"
          opacity="0.7"
        />
      </g>
    </g>
  )
}

/** Distant ranges, back two rows. */
export function FarRanges() {
  return (
    <>
      <polygon points={pts(RANGE_FAR)} fill={tr(0.28)} />
      <polygon points={pts(RANGE_MID)} fill={tr(0.22)} />
    </>
  )
}

/* ===========================================================================
   THE CONTINUITY DEVICES

   These are what make the page ONE experience rather than a hero followed by a
   marketing site. Both derive from the geometry above, so the terrain, the
   contours and the charts downstream are not "mountain-themed" — they are
   literally the same mountain, re-projected.
   =========================================================================== */

/**
 * THE SKYLINE, as a normalised series.
 *
 * The West Ridge and the Southeast Ridge, sampled left-to-right and rescaled
 * into 0..1 on both axes. Downstream sections plot it as a price line.
 *
 * This is the single most important export in the file. When section 03 draws
 * "the market" and the curve is Everest's actual profile, the transition from
 * mountain to data is not a metaphor the copy has to assert — the reader
 * recognises the shape, and the page earns the claim silently. A chart of
 * invented numbers next to a mountain would just be two pictures.
 */
export const SKYLINE = (() => {
  const raw = [...WEST_RIDGE].reverse().concat(SE_RIDGE.slice(1))
  const xs = raw.map((p) => p[0])
  const ys = raw.map((p) => p[1])
  const x0 = Math.min(...xs)
  const x1 = Math.max(...xs)
  const y0 = Math.min(...ys)
  const y1 = Math.max(...ys)
  return raw.map(([x, y]) => [(x - x0) / (x1 - x0), 1 - (y - y0) / (y1 - y0)])
})()

/**
 * CONTOURS OF THIS PEAK.
 *
 * Successive insets of the real massif silhouette, contracted toward the
 * summit — so the rings are the topographic map of the mountain the reader has
 * just been looking at, not a generic set of arcs. The eye recognises the
 * outline even when it cannot say why, which is what makes the mountain ->
 * terrain transition land.
 *
 * @param {number} count  number of rings
 * @param {number} at     0..1 — how far the rings have "grown in"
 */
/**
 * The point strings for `count` nested contour rings, outermost first.
 *
 * Exposed separately so a caller can animate rings INDIVIDUALLY — section 02
 * draws the map outward from the summit, one ring at a time, which needs a
 * MotionValue per ring rather than one opacity on the group.
 */
export function contourRings(count = 9) {
  const focus = APEX
  const skyline = [...WEST_RIDGE].reverse().concat(SE_RIDGE.slice(1))

  return Array.from({ length: count }).map((_, i) => {
    /* Rings start already well inside the silhouette. Beginning near k=0 made
       the outermost ring almost the full skyline — a 1,500px arc sweeping out
       of the frame across the foreground, which read as a stray swoosh rather
       than as a contour of the peak. Contours belong ON the mountain. */
    const k = 0.26 + (i / Math.max(1, count - 1)) * 0.66
    return pts(
      skyline.map(([x, y]) => [
        focus[0] + (x - focus[0]) * (1 - k * 0.86),
        focus[1] + (y - focus[1]) * (1 - k * 0.86),
      ]),
    )
  })
}

export function MassifContours({ count = 9, stroke = 'var(--border-strong)', className = '' }) {
  const focus = APEX

  /*
   * THE SKYLINE ONLY — not the closed silhouette.
   *
   * Contracting the full outline included its base: the two frame edges and the
   * straight run along y=900. Scaled down, those became long straight diagonals
   * cutting across the composition, which read as stray rules rather than as
   * contours and made the background look like a mistake.
   *
   * A contour line around a peak is an OPEN arc. Using just the West and
   * Southeast ridges gives exactly that, and nesting them produces the familiar
   * stacked-arc topographic map of this specific mountain.
   */
  const skyline = [...WEST_RIDGE].reverse().concat(SE_RIDGE.slice(1))

  return (
    <g className={className} fill="none" stroke={stroke}>
      {Array.from({ length: count }).map((_, i) => {
        /* Rings start already well inside the silhouette. Beginning near k=0 made
       the outermost ring almost the full skyline — a 1,500px arc sweeping out
       of the frame across the foreground, which read as a stray swoosh rather
       than as a contour of the peak. Contours belong ON the mountain. */
    const k = 0.26 + (i / Math.max(1, count - 1)) * 0.66
        const ring = skyline.map(([x, y]) => [
          focus[0] + (x - focus[0]) * (1 - k * 0.86),
          focus[1] + (y - focus[1]) * (1 - k * 0.86),
        ])
        return (
          <polyline
            key={i}
            points={pts(ring)}
            strokeWidth={i === 0 ? 1.4 : 1}
            opacity={1 - i * 0.07}
          />
        )
      })}
    </g>
  )
}

export { MASSIF_OUTLINE, NUPTSE_OUTLINE, pts, RIDGES, WEST_RIDGE }
